<a href="https://colab.research.google.com/github/dtype2100/Python/blob/master/zero_plus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 시간 앞에 0 추가하기

In [1]:
import pandas as pd

In [2]:
data = pd.DataFrame({'A': [0, 0, 0],
                     'B': [900, 900, 900],
                     'C': [1500, 1500, 1500]})
data

   A    B     C
0  0  900  1500
1  0  900  1500
2  0  900  1500

In [3]:
data['D'] = ['0' + str(x) for x in data['A'] if len(str(x)) == 3 or len(str(x)) == 1]
data['E'] = ['0' + str(x) for x in data['B'] if len(str(x)) == 3 or len(str(x)) == 1]
data['F'] = ['0' + str(x) if len(str(x)) == 3 or len(str(x)) == 1 else x for x in data['C']]

In [4]:
data

   A    B     C   D     E     F
0  0  900  1500  00  0900  1500
1  0  900  1500  00  0900  1500
2  0  900  1500  00  0900  1500